name: unspalsh
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 8.1.2
  bloc: 8.1.1
  json_serializable: ^6.6.1
  retrofit: ^4.0.1
  get_it: ^7.2.0
  photo_view: ^0.14.0
  json_annotation: ^4.8.0
  dio: 5.1.1
  equatable: ^2.0.5

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^6.0.0+1
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
